### ISSUE TITLE
В переменных не учитываются Mode

### ISSUE THREAD

**Issue by Counserf** [maxdenaro/inspect-styles-feedback#6]
В фигма выбран Mode: Dark.
Исходный цвет: #fff
Цвет Dark: #353535

:root не меняется (не дублируется как: [data-theme="dark"])
https://i.imgur.com/xlt0SYy.png

Вариант реализации:
**Цвета (переменные):**
```css
:root {
    --example: #353535;
}
```
**Раскрыть темы**
_____
**Как включить смену темы** (и условная ссылка на простейший гайд)
```css
[data-theme="dark"] {
    --example: #353535;
}

```
